name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # cada 12 horas
  workflow_dispatch: # para ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          COMMIT_MSG: "⚡ Actualizando actividad reciente"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
