name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run README update script
        uses: erwin09/erwin09@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
